import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "./components/ui/top-nav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-slate-800 to-gray-900 font-linux-libertine`}
      >
        <TopNav />
        {children}
      </body>
    </html>
  );
}
