version: '3.8'
services:
  app:
    image: wiki-race-fe
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"